apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: c:\programdata\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o k8s-manifests
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: planning-mongo
  name: planning-mongo
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: planning-mongo
