apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: recettes-pg-data
  name: recettes-pg-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
